#----------------------
# About section

blurb: <p>Jiyue (Gill) Huang visited City University of Hong Kong as an exchange student in 2016, and received her BS degree in electronic information engineering from Tianjin University, China, in 2017. She received her master degree in computer science at Peking University, China. She is now working towards her doctor degree in the Distributed System group at TU Delft. Her research is mainly focused in the area of federated learning incentives and attacks.</p>

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school: King's College London, description: Teaching students chemistry isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: King's College London, description: At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school: King's College London, description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>J.Huang-4@tudelft.nl<br>Distributed System Group,<br>Software Technology, EEMCS,<br>Delft University of Technology,<br>Netherlands.</p>


contact-links:
  # - {contact-text: Github, contact-link: "https://github.com/GillHwang", icon: 'favicon.html'}

